# Site settings
url: "http://reload.me.uk"
baseurl: "/talk-the-step-after-styleguides"

sass:
  sass_dir: .

kramdown:
  input: GFM

exclude: [README.md, Gemfile, Gemfile.lock]
markdown: kramdown
safe: true
lsi: false
